name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ARCH: ['x86_64', 'i686', 'armhf', 'aarch64']

    env:
      ARCH: ${{ matrix.ARCH }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up QEMU integration for Docker
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build in Docker container
        run: |
          bash -ex ci/build-in-docker.sh

      - name: Debug
        run: |
          set -x
          pwd
          find
          ls appimagetool*.AppImage*

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: appimagetool-${{ matrix.ARCH }}.build
          path: |
            **/appimagetool*.AppImage*

  upload:
    name: Create release and upload artifacts
    needs:
      - build
    runs-on: ubuntu-20.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
          chmod +x pyuploadtool-x86_64.AppImage
          ./pyuploadtool-x86_64.AppImage **/appimagetool*.AppImage*
