name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ARCH: x86_64
            RUNS_ON: ubuntu-24.04
          - ARCH: i686
            RUNS_ON: ubuntu-24.04
          - ARCH: aarch64
            RUNS_ON: ubuntu-24.04-arm
          - ARCH: armhf
            RUNS_ON: ubuntu-24.04-arm

    name: Build ${{ matrix.ARCH }}

    runs-on: ${{ matrix.RUNS_ON }}

    env:
      ARCH: ${{ matrix.ARCH }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build in Docker container
        run: |
          bash -ex ci/build-in-docker.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # Artifact name
          name: appimagetool-${{ matrix.ARCH }}.build
          path: |
            **/appimagetool*.AppImage*

  upload:
    name: Create release and upload artifacts
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
          chmod +x pyuploadtool-x86_64.AppImage
          GITHUB_CONTINUOUS_RELEASE_TYPE=stable ./pyuploadtool-x86_64.AppImage **/appimagetool*.AppImage*
